language: node_js
before_script:
  - npm install -g polymer-cli
  - polymer install --variants
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sauce_connect: true
script:
  - xvfb-run polymer test -l chrome
  - xvfb-run polymer test -l firefox
dist: trusty
